/*
** EPITECH PROJECT, 2019
** OOP_rtype_2019
** File description:
** R-Type General Header
*/

#pragma once

#ifndef COMPONENT_HPP_
#define COMPONENT_HPP_

#define COMPONENT_POSITION "POSITION"
#define COMPONENT_HORIZONTAL_MOVE "HORIZONTAL"
#define COMPONENT_BOUNCE_MOVE "BOUNCE"
#define COMPONENT_TEAM "TEAM"
#define COMPONENT_SCORE "SCORE"
#define COMPONENT_AUDIO "AUDIO"
#define COMPONENT_RANDOM_GUN "RAND_GUN"
#define COMPONENT_DRAWABLE "DRAWABLE"
#define COMPONENT_HITBOX "HITBOX"
#define COMPONENT_INPUTMOVE "INPUTMOVE"

#endif /* !RTYPE_HPP_ */